2025-04-10 16:07:30,080 - INFO - Preparing data...
2025-04-10 16:07:33,014 - INFO - Load dataset info from C:\Users\niksh\tensorflow_datasets\emnist\letters\3.1.0
2025-04-10 16:07:33,095 - INFO - Creating a tf.data.Dataset reading 1 files located in folders: C:\Users\niksh\tensorflow_datasets\emnist\letters\3.1.0.
2025-04-10 16:07:33,441 - INFO - Constructing tf.data.Dataset emnist for split train, from C:\Users\niksh\tensorflow_datasets\emnist\letters\3.1.0
2025-04-10 16:07:33,738 - INFO - Building model...
2025-04-10 16:07:34,340 - INFO - Training model...
2025-04-10 16:07:35,597 - ERROR - Training failed: ctc_batch_cost() missing 2 required positional arguments: 'input_length' and 'label_length'
Traceback (most recent call last):
  File "C:\Users\niksh\Desktop\DA5402-Assign-8\src\train.py", line 39, in train_model
    history = model.fit(train_data, validation_data=val_data, epochs=20)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\niksh\Desktop\DA5402-Assign-8\venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\niksh\Desktop\DA5402-Assign-8\venv\Lib\site-packages\keras\src\losses\losses.py", line 33, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ctc_batch_cost() missing 2 required positional arguments: 'input_length' and 'label_length'
